databases:
  - name: blog
    databaseName: blog_c3w4
    user: blog_c3w4_user

services:
  - type: web
    name: mysite
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog_c3w4
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false